In [1]:
!git remote add origin https://github.com/pandalabme/notebooks.git

fatal: not a git repository (or any parent up to mount point /home/jovyan)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).


In [8]:
import torch
import numpy as np
from matplotlib_inline import backend_inline
import matplotlib.pyplot as plt


def use_svg_display():
    backend_inline.set_matplotlib_formats('svg')


def set_figsize(figsize=(3.5, 2.5)):
    use_svg_display()
    plt.rcParams(


In [7]:
use_svg_display()

In [9]:
b = np.arange(2,8)
b

array([2, 3, 4, 5, 6, 7])

In [5]:
a = torch.arange(24).reshape(2, 3, 4)
a.numel(), len(a)

(24, 2)

In [6]:
a

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [11]:
a.sum(axis=0),a.sum(axis=0).shape

(tensor([[12, 14, 16, 18],
         [20, 22, 24, 26],
         [28, 30, 32, 34]]),
 torch.Size([3, 4]))

In [12]:
a.sum(axis=1),a.sum(axis=1).shape

(tensor([[12, 15, 18, 21],
         [48, 51, 54, 57]]),
 torch.Size([2, 4]))

In [13]:
a.sum(axis=2),a.sum(axis=2).shape

(tensor([[ 6, 22, 38],
         [54, 70, 86]]),
 torch.Size([2, 3]))

In [17]:
b = torch.arange(1).reshape(-1,1)
b

tensor([[0]])

In [18]:
a+b

tensor([[0, 1, 2, 3, 4, 5]])

In [4]:
a.numel()

6

In [24]:
a.float().norm()

tensor(65.7571)

In [27]:
torch.linalg.norm(a.float())

tensor(65.7571)

In [28]:
torch.linalg.norm(a.float(),axis=0)

tensor([[12.0000, 13.0384, 14.1421, 15.2971],
        [16.4924, 17.7200, 18.9737, 20.2485],
        [21.5407, 22.8473, 24.1661, 25.4951]])